package com.wizardev.smallplanmvp.data.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wizardev.smallplanmvp.data.Plan;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PLAN".
*/
public class PlanDao extends AbstractDao<Plan, Long> {

    public static final String TABLENAME = "PLAN";

    /**
     * Properties of entity Plan.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Something = new Property(1, String.class, "something", false, "SOMETHING");
        public final static Property Time = new Property(2, String.class, "time", false, "TIME");
        public final static Property Flag = new Property(3, int.class, "flag", false, "FLAG");
        public final static Property RemindDate = new Property(4, java.util.Date.class, "remindDate", false, "REMIND_DATE");
    }


    public PlanDao(DaoConfig config) {
        super(config);
    }
    
    public PlanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PLAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SOMETHING\" TEXT NOT NULL ," + // 1: something
                "\"TIME\" TEXT NOT NULL ," + // 2: time
                "\"FLAG\" INTEGER NOT NULL ," + // 3: flag
                "\"REMIND_DATE\" INTEGER);"); // 4: remindDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PLAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Plan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getSomething());
        stmt.bindString(3, entity.getTime());
        stmt.bindLong(4, entity.getFlag());
 
        java.util.Date remindDate = entity.getRemindDate();
        if (remindDate != null) {
            stmt.bindLong(5, remindDate.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Plan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getSomething());
        stmt.bindString(3, entity.getTime());
        stmt.bindLong(4, entity.getFlag());
 
        java.util.Date remindDate = entity.getRemindDate();
        if (remindDate != null) {
            stmt.bindLong(5, remindDate.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Plan readEntity(Cursor cursor, int offset) {
        Plan entity = new Plan( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // something
            cursor.getString(offset + 2), // time
            cursor.getInt(offset + 3), // flag
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)) // remindDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Plan entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSomething(cursor.getString(offset + 1));
        entity.setTime(cursor.getString(offset + 2));
        entity.setFlag(cursor.getInt(offset + 3));
        entity.setRemindDate(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Plan entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Plan entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Plan entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
